"""Update dead column to int and add fruits column

Revision ID: 06e9c75e3db6
Revises: fee39bcacd13
Create Date: 2025-03-23 13:39:29.856658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e9c75e3db6'
down_revision = 'fee39bcacd13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pepper_plant', schema=None) as batch_op:
        batch_op.alter_column('dead',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('fruits',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pepper_plant', schema=None) as batch_op:
        batch_op.alter_column('fruits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dead',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
