"""Initial migration

Revision ID: eabc407347fc
Revises: 
Create Date: 2025-03-23 15:03:29.966703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabc407347fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pepper_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_type', sa.String(length=50), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('seeds', sa.Integer(), nullable=False),
    sa.Column('germinated', sa.Integer(), nullable=False),
    sa.Column('seedlings', sa.Integer(), nullable=False),
    sa.Column('hardening', sa.Integer(), nullable=False),
    sa.Column('plants', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dead', sa.Integer(), nullable=True),
    sa.Column('fruits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('pepper_plant')
    # ### end Alembic commands ###
