"""Add fruits column to PepperPlant model

Revision ID: fee39bcacd13
Revises: 2b2d405795c6
Create Date: 2025-03-23 13:30:07.258527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee39bcacd13'
down_revision = '2b2d405795c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pepper_plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dead', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fruits', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pepper_plant', schema=None) as batch_op:
        batch_op.drop_column('fruits')
        batch_op.drop_column('dead')

    # ### end Alembic commands ###
